server:
  port: 8203

spring:
  application:
    name: service-user
  redis:
    host: 192.168.123.130
    port: 6379
    database: 2 # 使用2号数据库
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 5
        min-idle: 0
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.123.130:8848
    stream:
      binders: # 在此处配置要绑定的rabbitmq的服务信息；
        defaultRabbit: # 表示定义的名称，用于于binding整合
          type: rabbit # 消息组件类型
          environment: # 设置rabbitmq的相关的环境配置
            spring:
              rabbitmq:
                host: 192.168.123.130
                port: 5672
                username: root
                password: 123321
      bindings: # 服务的整合处理
        output: # 这个名字是一个通道的名称
          destination: exchange.direct.email # 表示要使用的Exchange名称定义
          content-type: application/json # 设置消息类型，本次为json，文本则设置“text/plain”
          binder: defaultRabbit # 设置要绑定的消息服务的具体设置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.123.130:3306/tmall_user?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8
    username: root
    password: 123321

# 指定mapper的.xml文件路径
mybatis-plus:
  mapper-locations: classpath:com/study/tmall/user/mapper/xml/*.xml

# 微信登录测试号相关信息
wx:
  open:
    app_id: wxff5db53def71d004
    app_secret: 59b0368ba1dd14266d389fab707fc331
    redirect_url: http://cvg6bv.natappfree.cc/api/user/weChat/callback # 二维码扫码成功后的回调地址