server:
  port: 8206

spring:
  application:
    name: service-task
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.123.130:8848
    stream:
      binders: # 在此处配置要绑定的rabbitmq的服务信息；
        defaultRabbit: # 表示定义的名称，用于于binding整合
          type: rabbit # 消息组件类型
          environment: # 设置rabbitmq的相关的环境配置
            spring:
              rabbitmq:
                host: 192.168.123.130
                port: 5672
                username: root
                password: 123321
      bindings: # 服务的整合处理
        timerPayTaskSend: # 计时器支付任务发送
          destination: exchange.direct.task # 表示要使用的Exchange名称定义
          content-type: application/json # 设置消息类型，本次为json，文本则设置“text/plain”
          binder: defaultRabbit # 设置要绑定的消息服务的具体设置
        timerReviewTaskSend: # 计时器评价任务发送
          destination: exchange.direct.task # 表示要使用的Exchange名称定义
          content-type: application/json # 设置消息类型，本次为json，文本则设置“text/plain”
          binder: defaultRabbit # 设置要绑定的消息服务的具体设置

# 序列化文件存储路径
file:
  save:
    path:
      pay-task: E:/JavaProject/study/tmall-v1.0/tmall-parent/service/service-task/src/main/resources/payTaskQueue.dat
      review-task: E:/JavaProject/study/tmall-v1.0/tmall-parent/service/service-task/src/main/resources/reviewTaskQueue.dat