server:
  port: 80

spring:
  application:
    name: service-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.123.130:8848
    # 使用服务发现路由
    gateway:
      discovery:
        locator:
          enabled: true
      routes: # - 表示这个属性可以有多个，也可以理解为表示数组
        - id: service-category #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: lb://service-category #匹配后提供服务的路由地址
          predicates:
            - Path=/*/category/**

        - id: service-product #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: lb://service-product #匹配后提供服务的路由地址
          predicates:
            - Path=/*/product/**

        - id: service-user #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: lb://service-user #匹配后提供服务的路由地址
          predicates:
            - Path=/*/user/**

        - id: service-order #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: lb://service-order #匹配后提供服务的路由地址
          predicates:
            - Path=/*/order/**