server:
  port: 8204

spring:
  application:
    name: service-order
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.123.130:8848
    stream:
      binders: # 在此处配置要绑定的rabbitmq的服务信息；
        defaultRabbit: # 表示定义的名称，用于于binding整合
          type: rabbit # 消息组件类型
          environment: # 设置rabbitmq的相关的环境配置
            spring:
              rabbitmq:
                host: 192.168.123.130
                port: 5672
                username: root
                password: 123321
      bindings: # 服务的整合处理
        dealNotifySend: # 交易状态通知通道
          destination: exchange.direct.deal # 表示要使用的Exchange名称定义
          content-type: application/json # 设置消息类型，本次为json，文本则设置“text/plain”
          binder: defaultRabbit # 设置要绑定的消息服务的具体设置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.123.130:3306/tmall_order?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8
    username: root
    password: 123321
  redis:
    host: 192.168.123.130
    port: 6379
    database: 3 # 使用3号数据库
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 5
        min-idle: 0

# 指定mapper的.xml文件路径
mybatis-plus:
  mapper-locations: classpath:com/study/tmall/order/mapper/xml/*.xml
  configuration: # 打印sql语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 尚硅谷的微信支付商户（后续自己开通商户用自己的）
weixin:
  pay:
    appid: wx74862e0dfcf69954 # 关联的公众号appid
    partner: 1558950191 # 商户号
    partnerkey: T6m9iK73b0kn9g5v426MKfHQH7X8rKwb # 商户key
  # 证书
  cert: E:\\JavaProject\\study\\tmall-v1.0\\tmall-parent\\service\\service-order\\src\\main\\resources\\cert

