server:
  port: 8204

spring:
  application:
    name: service-order
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.123.130:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.123.130:3306/tmall_order?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8
    username: root
    password: 123321
  redis:
    host: 192.168.123.130
    port: 6379
    database: 3 # 使用3号数据库
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 5
        min-idle: 0

# 指定mapper的.xml文件路径
mybatis-plus:
  mapper-locations: classpath:com/study/tmall/order/mapper/xml/*.xml
  configuration: # 打印sql语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 尚硅谷的微信支付商户（后续自己开通商户用自己的）
weixin:
  pay:
    appid: wx74862e0dfcf69954 # 关联的公众号appid
    partner: 1558950191 # 商户号
    partnerkey: T6m9iK73b0kn9g5v426MKfHQH7X8rKwb # 商户key
  cert: E:\\JavaProject\\study\\tmall-v1.0\\tmall-parent\\service\\service-order\\src\\main\\resources\\cert

